FROM python:3.5-slim

ENV RASA_NLU_DOCKER="YES" \
    RASA_NLU_HOME=/app \
    RASA_NLU_PYTHON_PACKAGES=/usr/local/lib/python3.5/dist-packages

# hack for installing default-jre (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199)
RUN mkdir -p /usr/share/man/man1
RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends build-essential git-core default-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR ${RASA_NLU_HOME}

COPY ./alt_requirements/ ${RASA_NLU_HOME}/alt_requirements/

RUN pip install -r alt_requirements/requirements_spacy_sklearn.txt
RUN pip install duckling==1.7.3
RUN pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz --no-cache-dir > /dev/null \
    && python -m spacy link en_core_web_sm en

COPY . ${RASA_NLU_HOME}

RUN pip install -e .

COPY config/custom_pipeline.json ${RASA_NLU_HOME}/config.json

VOLUME ["${RASA_NLU_HOME}/projects", "${RASA_NLU_HOME}/logs", "${RASA_NLU_HOME}/data"]

EXPOSE 5000

ENTRYPOINT ["./entrypoint.sh"]
CMD ["start", "-c", "config.json"]
